apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: supply-core-artifacts
  namespace: supply-core
spec:
  accessModes: [ReadWriteOnce]
  storageClassName: nfs-studio
  resources:
    requests:
      storage: 1Gi
